"""add lead_tags junction table

Revision ID: a2c71a69f650
Revises: a15274bf6fc9
Create Date: 2026-07-16 00:26:10.046413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c71a69f650'
down_revision: Union[str, Sequence[str], None] = 'a15274bf6fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_tags',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tagged_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tagged_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    op.create_index('ix_lead_tags_lead', 'lead_tags', ['lead_id'], unique=False)
    op.create_index('ix_lead_tags_tag', 'lead_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lead_tags_tag', table_name='lead_tags')
    op.drop_index('ix_lead_tags_lead', table_name='lead_tags')
    op.drop_table('lead_tags')
    # ### end Alembic commands ###
